### ISSUE TITLE
requirements.txt doesn't include dataclasses

### ISSUE THREAD

**Issue by eniklas** [d3r3kk/steamingpile#5]
`dataclasses` is required via pip for Python 3.6, but isn't in `requirements.txt`. It should be added there, or the minimum version specified to be Python 3.7 in the readme.

**Comment by d3r3kk** [comment]
This is only required for folks who run Python < 3.7 unfortunately. Going to not fix this, as the 3.7+ versions are the latest and greatest and I won't be able to support anything more than Python vCurrent and Python vCurrent-1 at most.
